services:
  server:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: $PORT
      POSTGRES_JDBC_URL: $POSTGRES_JDBC_URL
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    depends_on:
      - db

  db:
    image: ${POSTGRES_IMAGE}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_DB: "kmp-sample"
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD